name: Build and Deploy Hugo site

on:
  push:
    branches:
      - main   # or master, whichever you use for Hugo source

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build site
        run: hugo --minify

      - name: Deploy to Pages repo
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PAT_TOKEN }}
          external_repository: andymalv/andymalv.github.io
          publish_branch: gh-pages 
          publish_dir: ./public
          commit_message: "deploy site from GitHub Actions"
          force_orphan: true
          keep_files: false
