name: Build and Deploy Hugo site

on:
  push:
    branches:
      - main   # or master, whichever you use for Hugo source

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build site
        run: hugo --minify

      # - name: Deploy to Pages repo
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     personal_token: ${{ secrets.GH_PAT}}
      #     # personal_token: ${{ secrets.GITHUB_TOKEN}}
      #     external_repository: andymalv/andymalv.github.io
      #     publish_branch: gh-pages 
      #     publish_dir: ./public
      #     # commit_message: "deploy site from GitHub Actions"
      #     force_orphan: true
      #     keep_files: false
      #
      - name: Deploy manually
        run: |
          cd public
    
          # Clean up any existing git stuff
          rm -rf .git
          rm -f .gitignore
    
          # Initialize fresh
          git init
          git config user.name "GitHub Actions"
          git config user.email "github-actions@users.noreply.github.com"
    
          # Add and commit
          git add .
          git status
          git commit -m "Deploy $(date +'%Y-%m-%d %H:%M:%S')"
    
          # Show what we're about to push
          echo "Pushing to: https://github.com/andymalv/andymalv.github.io.git"
          echo "Pushing branch: gh-pages"
    
          # Push with explicit URL and branch mapping
          git push -f https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/andymalv/andymalv.github.io.git HEAD:gh-pages
